# This workflow builds and pushes a Docker image to GitHub Container Registry on push to main
# Docs: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for MinVer to access tags

      # Using the minver CLI, compute the MinVer version and 
      # set MINVERVERSIONOVERRIDE which will be picked used by later steps.
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install MinVer CLI
        run: dotnet tool install -g minver-cli
      - name: Calculate version with MinVer
        id: minver
        run: |
          VER="$(minver)"
          #echo "value=$VER" >> "$GITHUB_OUTPUT"
          echo "MINVERVERSIONOVERRIDE=$VER" >> "$GITHUB_ENV"
          echo "Resolved MinVer version: $VER"

          # Parse major/minor for extra Docker tags (optional)
          MINVER_BASE="${VER%%-*}"          # strip -pre if present
          MINVER_MAJOR="${BASE%%.*}"
          MINVER_MINOR="${BASE%.*}"
          MINVER_PATCH=
          #echo "MAJOR=$MAJOR" >> "$GITHUB_ENV"
          #echo "MINOR=$MINOR" >> "$GITHUB_ENV"
          #echo "BASE=$BASE"   >> "$GITHUB_ENV"
      
      # Build and push Docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            MINVERVERSIONOVERRIDE=${{ env.MINVERVERSIONOVERRIDE }}
          tags: ghcr.io/${{ github.repository }}:${{ env.MINVERVERSIONOVERRIDE }}
